/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceUsuario;

import javax.swing.JOptionPane;

/**
 *
 * @author iara
 */
public class FrmGeral extends javax.swing.JFrame {

    /**
     * Creates new form FrmGeral
     */
    public FrmGeral() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnClienteCadastro = new javax.swing.JButton();
        btnClienteListagem = new javax.swing.JButton();
        btnProdutoCadastro = new javax.swing.JButton();
        btnProdutoListagem = new javax.swing.JButton();
        btnMetodoCadastro = new javax.swing.JButton();
        btnMetodoListagem = new javax.swing.JButton();
        btnVendaEfetuar = new javax.swing.JButton();
        btnVendaListar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Vendas");

        btnClienteCadastro.setText("Cadastro de Clientes");
        btnClienteCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClienteCadastroMouseClicked(evt);
            }
        });

        btnClienteListagem.setText("Listagem de Clientes");
        btnClienteListagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClienteListagemMouseClicked(evt);
            }
        });

        btnProdutoCadastro.setText("Cadastro de Produtos");
        btnProdutoCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProdutoCadastroMouseClicked(evt);
            }
        });

        btnProdutoListagem.setText("Listagem de Produtos");
        btnProdutoListagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProdutoListagemMouseClicked(evt);
            }
        });

        btnMetodoCadastro.setText("Cadastro Metodos de Pagamento");
        btnMetodoCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMetodoCadastroMouseClicked(evt);
            }
        });

        btnMetodoListagem.setText("Listagem Metodos de Pagamento");
        btnMetodoListagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMetodoListagemMouseClicked(evt);
            }
        });

        btnVendaEfetuar.setText("Efetuar Venda");
        btnVendaEfetuar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVendaEfetuarMouseClicked(evt);
            }
        });

        btnVendaListar.setText("Listar Vendas");
        btnVendaListar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVendaListarMouseClicked(evt);
            }
        });

        btnSair.setText("Sair");
        btnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSairMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnVendaEfetuar)
                    .addComponent(btnMetodoCadastro)
                    .addComponent(btnProdutoCadastro)
                    .addComponent(btnClienteCadastro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnClienteListagem)
                    .addComponent(btnProdutoListagem)
                    .addComponent(btnMetodoListagem)
                    .addComponent(btnVendaListar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(218, 218, 218))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClienteCadastro)
                    .addComponent(btnClienteListagem))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProdutoCadastro)
                    .addComponent(btnProdutoListagem))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMetodoCadastro)
                    .addComponent(btnMetodoListagem))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVendaEfetuar)
                    .addComponent(btnVendaListar))
                .addGap(28, 28, 28)
                .addComponent(btnSair)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseClicked
        if (JOptionPane.showConfirmDialog(rootPane, "Deseja Sair?") 
                == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_btnSairMouseClicked

    private void btnClienteCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClienteCadastroMouseClicked
        FrmCadastroCliente janela = new FrmCadastroCliente();
        janela.setVisible(true);
    }//GEN-LAST:event_btnClienteCadastroMouseClicked

    private void btnProdutoCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProdutoCadastroMouseClicked
        FrmCadastroProduto janela1 = new FrmCadastroProduto();
        janela1.setVisible(true);
    }//GEN-LAST:event_btnProdutoCadastroMouseClicked

    private void btnMetodoCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMetodoCadastroMouseClicked
        FrmCadastroMetodo janela2 = new FrmCadastroMetodo();
        janela2.setVisible(true);
    }//GEN-LAST:event_btnMetodoCadastroMouseClicked

    private void btnVendaEfetuarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVendaEfetuarMouseClicked
        FrmEfetuarVenda janela3 = new FrmEfetuarVenda();
        janela3.setVisible(true);
    }//GEN-LAST:event_btnVendaEfetuarMouseClicked

    private void btnMetodoListagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMetodoListagemMouseClicked
        FrmListagemMetodo janela = new FrmListagemMetodo();
        janela.setVisible(true);
    }//GEN-LAST:event_btnMetodoListagemMouseClicked

    private void btnClienteListagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClienteListagemMouseClicked
        FrmListagemCliente janela = new FrmListagemCliente();
        janela.setVisible(true);
    }//GEN-LAST:event_btnClienteListagemMouseClicked

    private void btnProdutoListagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProdutoListagemMouseClicked
        FrmListagemProduto janela = new FrmListagemProduto();
        janela.setVisible(true);
    }//GEN-LAST:event_btnProdutoListagemMouseClicked

    private void btnVendaListarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVendaListarMouseClicked
        FrmListagemVenda janela = new FrmListagemVenda();
        janela.setVisible(true);
    }//GEN-LAST:event_btnVendaListarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmGeral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmGeral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmGeral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmGeral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FrmGeral().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClienteCadastro;
    private javax.swing.JButton btnClienteListagem;
    private javax.swing.JButton btnMetodoCadastro;
    private javax.swing.JButton btnMetodoListagem;
    private javax.swing.JButton btnProdutoCadastro;
    private javax.swing.JButton btnProdutoListagem;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnVendaEfetuar;
    private javax.swing.JButton btnVendaListar;
    // End of variables declaration//GEN-END:variables
}
